<robot name="car_camera" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="camera_length" value="0.02" />
    <xacro:property name="camera_width" value="0.05" />
    <xacro:property name="camera_height" value="0.05" />
    <!-- 添加质量 -->
    <xacro:property name="camera_mass" value="0.02" />

    <xacro:property name="camera_x_bias" value="0.08" />
    <xacro:property name="camera_y_bias" value="0" />
    <xacro:property name="camera_z_bias" value="${car_base_hight / 2 + camera_height / 2}" />

    <link name="camera">
        <visual>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="camera_color">
                <color rgba="1 1 1 0.5" />
            </material>
        </visual>

        <!-- 添加碰撞检测 -->
        <collision>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <!-- 惯性矩阵 -->
        <xacro:Box_inertial_matrix m="${camera_mass}" l="${camera_length}" w="${camera_width}" h="${camera_height}" />
    </link>

    <!-- 添加颜色 -->
    <gazebo reference="camera" >
        <material>Gazebo/Gray</material>
    </gazebo>   

    <joint name="camera_joint_car_base" type="fixed">
        <parent link="car_base" />
        <child link="camera" />
        <origin xyz="${camera_x_bias} ${camera_y_bias} ${camera_z_bias}" rpy="0 0 0" />
    </joint>

</robot>