<robot name="my_car_move" xmlns:xacro="http://wiki.ros.org/xacro">

    <!-- 传动实现:用于连接控制器与关节 -->
    <xacro:macro name="joint_trans" params="joint_name">
        <!-- Transmission is important to link the joints and the controller -->
        <transmission name="${joint_name}_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${joint_name}">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            </joint>
            <actuator name="${joint_name}_motor">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>
    </xacro:macro>

    <!-- 每一个驱动轮都需要配置传动装置 -->
    <!-- 【注意】需要修改的地方是这里，意思是传动关节的名称 -->
    <!-- 在car_base.xacro 中找到驱动轮的 joint 宏 ${wheel_name}_joint_base-->
    <!-- 将这块写死，${wheel_name} 就用下面的调用 xacro:drive_wheel_func 中的 name -->
    <xacro:joint_trans joint_name="left_joint_base" />
    <xacro:joint_trans joint_name="right_joint_base" />

    <!-- 控制器 -->
    <gazebo>
        <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
            <rosDebugLevel>Debug</rosDebugLevel>
            <publishWheelTF>true</publishWheelTF>
            <robotNamespace>/</robotNamespace>
            <publishTf>1</publishTf>
            <publishWheelJointState>true</publishWheelJointState>
            <alwaysOn>true</alwaysOn>
            <updateRate>100.0</updateRate>
            <legacyMode>true</legacyMode>
            <!-- 这里设置关节名称 -->
            <leftJoint>left_joint_base</leftJoint> <!-- 左轮 -->
            <rightJoint>right_joint_base</rightJoint> <!-- 右轮 -->
            <!-- 这里设置车轮间距 : 车体半径 * 2-->
            <wheelSeparation>${car_base_radius * 2}</wheelSeparation> <!-- 车轮间距 -->
            <!-- 这里设置车轮直径 -->
            <wheelDiameter>${drive_wheel_radius * 2}</wheelDiameter> <!-- 车轮直径 -->
            <broadcastTF>1</broadcastTF>
            <wheelTorque>30</wheelTorque>
            <wheelAcceleration>1.8</wheelAcceleration>
            <!-- 控制运动的话题名 -->
            <commandTopic>cmd_vel</commandTopic> <!-- 运动控制话题 -->
            <!-- 里程计的坐标系和订阅话题 -->
            <odometryFrame>odom</odometryFrame> 
            <odometryTopic>odom</odometryTopic> <!-- 里程计话题 -->
            <!-- 机器人模型的根坐标系 -->
            <robotBaseFrame>footprint</robotBaseFrame> <!-- 根坐标系 -->
        </plugin>
    </gazebo>

</robot>