<?xml version="1.0"?>

<robot name="scout_mini"
    xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:arg name="robot_namespace" default="/" />
    <xacro:arg name="urdf_extras" default="empty.urdf" />

    <xacro:include filename="$(find scout_description)/urdf/scout_mini_wheel_1.xacro" />
    <xacro:include filename="$(find scout_description)/urdf/scout_mini_wheel_2.xacro" />
    <xacro:include filename="$(find scout_description)/urdf/scout_mini_wheel_3.xacro" />
    <xacro:include filename="$(find scout_description)/urdf/scout_mini_wheel_4.xacro" />

    <!-- Variables -->
    <xacro:property name="M_PI" value="3.14159"/>

    <!-- Vehicle Geometries -->
    <xacro:property name="base_x_size" value="0.6200000" />
    <xacro:property name="base_y_size" value="0.585000" />
    <xacro:property name="base_z_size" value="0.235000" />

    <xacro:property name="wheelbase" value="0.463951"/>
    <xacro:property name="track" value="0.416503"/>
    <xacro:property name="wheel_vertical_offset" value="-0.100998" />

    <xacro:property name="wheel_length" value="0.8e-01" />
    <xacro:property name="wheel_radius" value="1.600e-01" />

    <!-- Base link -->
    <link name="base_link">
        <visual>
            <origin
                    xyz="0 0 0.0"
                    rpy="1.57 0 1.57" />
            <geometry>
                <mesh filename="package://scout_description/meshes/scout_mini_base_link2.dae" />
            </geometry>
        </visual>
        <collision>
            <origin
                    xyz="0 0 0"
                    rpy="1.57 0 1.57" />
          <geometry>
            <mesh
              filename="package://scout_description/meshes/scout_mini_base_link2.dae" />
          </geometry>
        </collision>
    </link>

    <link name="inertial_link">
        <inertial>
            <mass value="60" />
            <origin xyz="0.0 0.0 0.0" />
            <inertia ixx="2.288641" ixy="0" ixz="0" iyy="5.103976" iyz="0" izz="3.431465" />
        </inertial>
    </link>

    <joint name="inertial_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="inertial_link" />
    </joint>

    <xacro:scout_mini_wheel_1 wheel_prefix="front_left">
        <origin xyz="${wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="-1.57 0 0" />
    </xacro:scout_mini_wheel_1>

    <xacro:scout_mini_wheel_2 wheel_prefix="rear_left">
        <origin xyz="${-wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="-1.57 0 0" />
    </xacro:scout_mini_wheel_2>

    <xacro:scout_mini_wheel_3 wheel_prefix="front_right">
        <origin xyz="${wheelbase/2} ${-track/2} ${wheel_vertical_offset+0.001}" rpy="1.57 0 0" />
    </xacro:scout_mini_wheel_3>

    <xacro:scout_mini_wheel_4 wheel_prefix="rear_right">
        <origin xyz="${-wheelbase/2} ${-track/2} ${wheel_vertical_offset+0.001}" rpy="1.57 0 0" />
    </xacro:scout_mini_wheel_4>

    <!-- Additional definitions -->
    <xacro:include filename="$(arg urdf_extras)" />

    <!-- Gazebo definitions  -->
    <xacro:include filename="$(find scout_description)/urdf/scout_mini.gazebo" />


    <!-- additional sensor -->
    <!-- self add 2D laser -->
    <xacro:include filename="$(find scout_description)/urdf/addition/2Dlaser.xacro" />
    <xacro:rplidar />
    <joint name="2Dlaser_joint_baselink" type="fixed" >
        <parent link="base_link" />
        <child link="2Dlaser_link" />   
        <origin xyz="0 0 ${wheel_vertical_offset * -1}" rpy="0 0 0"/>
    </joint>

    <!-- self add IMU-->  
    <xacro:include filename="$(find scout_description)/urdf/addition/IMU.xacro" />
    <xacro:imu />
    <joint name="imu_joint_baselink" type="fixed" >
        <parent link="base_link" />
        <child link="imu_link" />   
        <origin xyz="-0.2 0 ${(wheel_vertical_offset * -1) - 0.06}" rpy="0 0 0"/>
    </joint>

    <!-- self add Camera -->
    <xacro:include filename="$(find scout_description)/urdf/addition/Camera.xacro" />
    <joint name="usbcamera_joint_baselink" type="fixed" >
        <parent link="base_link" />
        <child link="usbcam_link" />
        <origin xyz="0.28 0 ${(wheel_vertical_offset * -1) - 0.06}" rpy="0 0 0" />
    </joint>



    <!-- self add base_footprint -->
    <link name="base_footprint" >
        <visual>
            <geometry>
                <sphere radius="0.0002" />
            </geometry>
        </visual>
    </link>
    <joint name="basefootprint_joint_baselink" type="fixed" >
        <parent link="base_footprint"/>
        <child link="base_link" />
        <origin xyz="0 0 ${(wheel_vertical_offset - 0.08) * -1}" rpy="0 0 0"/>
    </joint>

    <!-- self add move -->
    <!-- gazebo -->
    <xacro:include filename="$(find demo)/gazebo/move.xacro" />



</robot>
