global_costmap:
  global_frame: map 
  robot_base_frame: base_footprint 

  inflation_radius: 0.05
  cost_scaling_factor: 8.0

  update_frequency: 1.0
  publish_frequency: 1.0
  transform_tolerance: 1.0

  static_map: true 