<robot name="car_lader" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- 1.雷达支架 -->
    <xacro:property name="support_radius" value="0.01" />
    <xacro:property name="support_length" value="0.15" />
    <!-- 雷达支架偏移量 --> 
    <xacro:property name="support_x" value="0" />
    <xacro:property name="support_y" value="0" />
    <xacro:property name="support_z" value="${car_base_hight/2 + support_length / 2}" />


    <!-- 2.雷达尺寸 -->
    <xacro:property name="laser_radius" value="0.03" />
    <xacro:property name="laser_length" value="0.05" />
    <!-- 雷达偏移量 -->
    <xacro:property name="laser_x" value="0" />
    <xacro:property name="laser_y" value="0" />
    <xacro:property name="laser_z" value="${support_length / 2 + laser_length / 2}" />


    <!-- link 和 joint 实现 -->
    <!-- 连接杆 -->
    <link name="support">
        <visual>
            <geometry>
                <cylinder radius="${support_radius}" length="${support_length}" />
            </geometry>
            <material name="yellow">
                <color rgba="0.8 0.5 0 0.5" />
            </material> 
        </visual>
    </link>

    <joint name="support2base" type="fixed">
        <parent link="car_base" />
        <child link="support" />
        <origin xyz="${support_x} ${support_y} ${support_z}" rpy="0 0 0" />
    </joint>

    <!-- 雷达 -->
    <link name="laser">
        <visual>
            <geometry>
                <cylinder radius="${laser_radius}" length="${laser_length}" />
            </geometry>
            <material name="blue">
                <color rgba="0 0 1 0.5" />
            </material>
        </visual>
    </link>

    <joint name="lader2support" type="fixed">
        <parent link="support" />
        <child link="laser" />
        <origin xyz="${laser_x} ${laser_y} ${laser_z}" rpy="0 0 0" />
    </joint>


</robot>